
export const TEXTS = {
  ar: {
    ticker: "⚡️ عرض اليوم: شحن مجاني وسريع لأي مكان في الإمارات ⚡️",
    heroTitle: "اجعل قهوتك تتحدث عنك!",
    heroSub: "هل مللت من الأكواب التقليدية؟ صمّم طقمك الفاخر الآن ودع ألواننا المبهجة تزيّن صباحك.",
    cta: "دعنا نبدأ التجربة 🚀",
    back: "العودة",
    swipeMore: "اسحب للاكتشاف 🎨",
    swipePacks: "اسحب لاختيار الحجم 👇",
    freeDelivery: "توصيل مجاني",
    step1Title: "أي طقم يمثل أسلوبك؟",
    step2Title: "اختر ألوانك المفضلة",
    step3Title: "أين نرسل هذا الجمال؟",
    progress: "{x} من {n} تم اختيارها",
    total: "الإجمالي",
    cups: "أكواب",
    aed: "درهم",
    confirm: "تأكيد الطلب",
    successTitle: "يا أهلاً بك في Cupify!",
    orderCode: "رمز طلبك",
    whatsappMsg: "تواصل معنا عبر واتساب لسرعة التوصيل",
    fullName: "اسمك الكريم",
    mobile: "رقم التواصل",
    city: "مدينتك",
    address: "تفاصيل الموقع",
    morning: "صباحاً",
    evening: "مساءً",
    agree: "أوافق على الدفع عند المعاينة",
    validationError: "يرجى إكمال البيانات لنتمكن من خدمتك",
    changePack: "تغيير الطقم",
    randomHint: "تم اختيار ألوان عشوائية لك — يمكنك تغييرها بسهولة!"
  },
  en: {
    ticker: "⚡️ TODAY'S OFFER: FAST & FREE SHIPPING ACROSS UAE ⚡️",
    heroTitle: "Let Your Coffee Speak!",
    heroSub: "Tired of boring cups? Design your premium set now and let our vibrant colors brighten your day.",
    cta: "Start Now 🚀",
    back: "Back",
    swipeMore: "Swipe for Magic 🎨",
    swipePacks: "Swipe to pick size 👇",
    freeDelivery: "Free Shipping",
    step1Title: "Which set is yours?",
    step2Title: "Pick your favorites",
    step3Title: "Delivery Details",
    progress: "{x} of {n} selected",
    total: "Total",
    cups: "Cups",
    aed: "AED",
    confirm: "Confirm Order",
    successTitle: "Welcome to Cupify!",
    orderCode: "Order Code",
    whatsappMsg: "Chat on WhatsApp for faster delivery",
    fullName: "Full Name",
    mobile: "Mobile Number",
    city: "City",
    address: "Address",
    morning: "Morning",
    evening: "Evening",
    agree: "I agree to pay after inspection",
    validationError: "Please fill all details",
    changePack: "Change Pack",
    randomHint: "We picked random colors for you — feel free to change them!"
  }
};
